name: my_anime
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^2.0.1
  mwwm: ^2.0.0
  relation: ^3.1.0
  tabnavigator: ^1.0.0

  # DI
  surf_injector: ^1.0.0

  # хранение данных между сеансами
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^4.1.4

  # тестирование
  mocktail: ^0.1.4

  # генераторы
  hive_generator: ^1.1.0
  retrofit_generator: ^2.0.1
  build_runner: ^2.1.1
  dart_code_metrics: ^4.1.0

flutter:
  uses-material-design: true
